version: '3.8'
services:
  postingportalback:
    image: postingportalback
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PostingPortal
    ports:
      - "3307:3306"
  web:
    image: postingportalfront
    ports:
    - "7777:80"